package view;
import dao.BookDAO;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Book;
import controller.JPanelSaleController;
import dao.OrderDAO;
import dao.OrderDetailDAO;
import java.sql.Date;
import javax.swing.JOptionPane;
import model.Order;
import model.OrderDetail;
/**
 *
 * @author PC
 */
public class JPanelSale extends javax.swing.JPanel {

    /**
     * Creates new form JPanelOrder
     */
    public JPanelSale() {
        initComponents();
        act();
        table_product_list(BookDAO.getInstance().selectAll());
        setToday();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_product_list = new javax.swing.JTable();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_customer = new javax.swing.JButton();
        jLabel_customerId = new javax.swing.JLabel();
        jLabel_customerName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSpinner_payment = new javax.swing.JSpinner();
        jSpinner_delivery = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_note = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jButton_thanhToan = new javax.swing.JButton();
        jLabel_orderDate = new javax.swing.JLabel();
        jLabel_totalPrice = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_cart = new javax.swing.JTable();
        jButton_search = new javax.swing.JButton();
        jTextField_search = new javax.swing.JTextField();
        jButton_insert = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jTable_product_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Tác giả", "Giá (1000 VND)", "Tồn kho"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_product_list);

        jTabbedPane3.addTab("Danh sách sản phẩm", jScrollPane1);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Mã khách hàng :");

        jLabel2.setText("Tên khách hàng :");

        jButton_customer.setText("Khách hàng");

        jLabel_customerId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_customerId.setText("----");

        jLabel_customerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_customerName.setText("----");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButton_customer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_customerId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_customerName, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_customerId))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_customerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_customer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Ngày tạo :");

        jLabel5.setText("Tổng tiền :");

        jLabel6.setText("Hình thức thanh toán");

        jLabel7.setText("Hình thức giao hàng");

        jSpinner_payment.setModel(new javax.swing.SpinnerListModel(new String[] {"Tiền mặt", "Chuyển khoản", "Quẹt thẻ"}));

        jSpinner_delivery.setModel(new javax.swing.SpinnerListModel(new String[] {"Trực tiếp", "Giao tại nhà"}));

        jTextArea_note.setColumns(20);
        jTextArea_note.setRows(5);
        jScrollPane3.setViewportView(jTextArea_note);

        jLabel8.setText("Ghi chú :");

        jButton_thanhToan.setBackground(new java.awt.Color(204, 204, 0));
        jButton_thanhToan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_thanhToan.setForeground(new java.awt.Color(51, 51, 51));
        jButton_thanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dollar-icon.png"))); // NOI18N
        jButton_thanhToan.setText("Thanh toán");

        jLabel_orderDate.setText("----");

        jLabel_totalPrice.setText("----");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(jButton_thanhToan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(12, 12, 12)
                                .addComponent(jSpinner_payment))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel_orderDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel_totalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinner_delivery, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_orderDate))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel_totalPrice))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinner_payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinner_delivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_thanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Đơn hàng", jPanel4);

        jTable_cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_cart);

        jTabbedPane1.addTab("Giỏ hàng", jScrollPane2);

        jButton_search.setText("Tìm kiếm");

        jTextField_search.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton_insert.setText("Thêm sản phẩm");

        jButton_delete.setText("Xóa đơn hàng");

        jButton_reset.setText("Làm mới giỏ hàng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jButton_search)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_insert))
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jButton_reset)
                                .addGap(26, 26, 26)
                                .addComponent(jButton_delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_search)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_insert)))
                        .addGap(20, 20, 20)
                        .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_customer;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_insert;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JButton jButton_search;
    private javax.swing.JButton jButton_thanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_customerId;
    private javax.swing.JLabel jLabel_customerName;
    private javax.swing.JLabel jLabel_orderDate;
    private javax.swing.JLabel jLabel_totalPrice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner_delivery;
    private javax.swing.JSpinner jSpinner_payment;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable_cart;
    private javax.swing.JTable jTable_product_list;
    private javax.swing.JTextArea jTextArea_note;
    private javax.swing.JTextField jTextField_search;
    // End of variables declaration//GEN-END:variables
    int rowIndex_product_list;
    int rowIndex_cart;
    String customerId="----";
    String customerName="----";
    
    public void act(){
        ActionListener actionListener = new JPanelSaleController(this);
        jButton_customer.addActionListener(actionListener);
        jButton_delete.addActionListener(actionListener);
        jButton_insert.addActionListener(actionListener);
        jButton_reset.addActionListener(actionListener);
        jButton_search.addActionListener(actionListener);
        jButton_thanhToan.addActionListener(actionListener);
        
    }
    
    public void table_product_list(ArrayList<Book> arr){
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        jTable_product_list.setModel(defaultTableModel);

        defaultTableModel.addColumn("Mã SP");
        defaultTableModel.addColumn("Tên SP");
        defaultTableModel.addColumn("Tác giả");
        defaultTableModel.addColumn("Giá");
        defaultTableModel.addColumn("Tồn kho");
        
        for(Book book : arr){
            defaultTableModel.addRow(book.getToTabble());
        }       
    }
    
    public void search (){
        table_product_list(BookDAO.getInstance().search(jTextField_search.getText()));
    }
    
    public void add_product(int amount){         // amount <inventory ? true : false
        try{
            rowIndex_product_list = jTable_product_list.getSelectedRow();
            String book_id = String.valueOf(jTable_product_list.getValueAt(rowIndex_product_list, 0));
            String book_name = String.valueOf(jTable_product_list.getValueAt(rowIndex_product_list, 1));
            String price = String.valueOf(jTable_product_list.getValueAt(rowIndex_product_list, 3));
            String inventory_number_str = String.valueOf(jTable_product_list.getValueAt(rowIndex_product_list, 4));
            int inventory_number = Integer.valueOf(inventory_number_str);

            if(amount>inventory_number)
                return;
            DefaultTableModel defaultTableModel = (DefaultTableModel)jTable_cart.getModel();
//            jTable_cart.setModel(defaultTableModel);
//            defaultTableModel.addColumn("Mã sản phẩm");
//            defaultTableModel.addColumn("Tên sản phẩm");
//            defaultTableModel.addColumn("Đơn giá");
//            defaultTableModel.addColumn("Số lượng");

            Object[] data_cart = new Object[4];
            data_cart[0] = book_id;
            data_cart[1] = book_name;
            data_cart[2] = price;
            data_cart[3] = amount;

            defaultTableModel.addRow(data_cart);
            setTotalPrice();

        }catch(java.lang.ArrayIndexOutOfBoundsException e){
            return ;
        }
    }
    
    public void delete(){
        try{
            rowIndex_cart = jTable_cart.getSelectedRow();

            DefaultTableModel defaultTableModel = (DefaultTableModel)jTable_cart.getModel();

            defaultTableModel.removeRow(rowIndex_cart);
            setTotalPrice();

        }catch(java.lang.ArrayIndexOutOfBoundsException e){
            return ;
        }
    }
    
    public void reset(){
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        jTable_cart.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("Mã sản phẩm");
        defaultTableModel.addColumn("Tên sản phẩm");
        defaultTableModel.addColumn("Đơn giá");
        defaultTableModel.addColumn("Số lượng");
        jLabel_totalPrice.setText("----");
        jLabel_customerId.setText("----");
        jLabel_customerName.setText("----");
    }
    
    public boolean ThanhToan(){
        String customer_id_string = String.valueOf(jLabel_customerId.getText());
        if(customer_id_string.equals("----")){
            JOptionPane.showMessageDialog(jButton_insert, "Chưa chọn khách hàng");
            return false;
        }
        String createDate_string = String.valueOf(jLabel_orderDate.getText());
        String totalPrice_string = String.valueOf(jLabel_totalPrice.getText());
        String payment = String.valueOf(jSpinner_payment.getValue());
        String delivery = String.valueOf(jSpinner_delivery.getValue());
        String note = String.valueOf(jTextArea_note.getText());
        int customer_id = Integer.valueOf(customer_id_string);
        Date createDate = Date.valueOf(createDate_string);
        int totalPrice = Integer.valueOf(totalPrice_string.substring(0, totalPrice_string.indexOf(" ")));
        Order order = new Order(customer_id, createDate, totalPrice, payment, delivery, note);
        OrderDAO.getInstance().insert(order);
        
        insert_orderDetail();
        return  true;
    }
    
    public void setToday(){
        long millis = System.currentTimeMillis();
        Date today = new Date(millis);
        jLabel_orderDate.setText(String.valueOf(today));
    }
    
    public void setCustomer(){
        jLabel_customerId.setText(customerId);
        jLabel_customerName.setText(customerName);
    }
    
    public void setTotalPrice(){
        int totalPrice = 0;
        int size = jTable_cart.getRowCount();
        if(size==0)
            return;
        for(int i=0;i<size;i++){
            String price_string = String.valueOf(jTable_cart.getValueAt(i, 2));
            String amount_string = String.valueOf(jTable_cart.getValueAt(i, 3));
            int price =Integer.valueOf(price_string);
            int amount =Integer.valueOf(amount_string);
            totalPrice +=price*amount;            
        }
        jLabel_totalPrice.setText(totalPrice+" 000 VNĐ");       
    }
    public boolean isSelected_table_product_list(){
        for(int i=0;i<jTable_product_list.getRowCount();i++){
            if(jTable_product_list.isRowSelected(i)){
                return true;
            }
        }
        return false;
    }
    
    public boolean isSelected_table_cart(){
        for(int i=0;i<jTable_cart.getRowCount();i++){
            if(jTable_cart.isRowSelected(i)){
                return true;
            }
        }
        return false;
    }
    
    public void insert_orderDetail(){
        for(int i=0;i<jTable_cart.getRowCount();i++){
            int book_id = Integer.valueOf(String.valueOf(jTable_cart.getValueAt(i, 0)));
//            String book_name = String.valueOf(jTable_cart.getValueAt(i, 1));
            int price = Integer.valueOf(String.valueOf(jTable_cart.getValueAt(i, 2)));
            int quantity = Integer.valueOf(String.valueOf(jTable_cart.getValueAt(i, 3)));
            int total = price * quantity;
            int order_id = OrderDetailDAO.getInstance().last_insert_id();
            OrderDetail orderDetail = new OrderDetail(order_id, book_id, quantity, price, total);
            OrderDetailDAO.getInstance().insert(orderDetail);

        }
    }
    

}
