package view;

import controller.JPanelCustomerController;
import dao.CustomerDAO;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;
import model.Customer;

/**
 *
 * @author PC
 */
public class JPanelCustomer extends javax.swing.JPanel {

    /**
     * Creates new form JPanelCustomer
     */
    public JPanelCustomer() {
        initComponents();
        act();
        table(CustomerDAO.getInstance().selectAll());
        jButton_save.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jTextField_phone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_address = new javax.swing.JTextArea();
        jLabel_id = new javax.swing.JLabel();
        jRadioButton_on = new javax.swing.JRadioButton();
        jRadioButton_off = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jButton_add = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_save = new javax.swing.JButton();
        jTabbedPane_history = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_customer = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton_search = new javax.swing.JButton();
        jTextField_search = new javax.swing.JTextField();
        jSpinner_filter = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jPanel_history = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_history = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mã khách hàng");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tên khách hàng");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Số điện thoại");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Địa chỉ");

        jLabel5.setText("Trạng thái");

        jTextArea_address.setColumns(20);
        jTextArea_address.setRows(5);
        jScrollPane1.setViewportView(jTextArea_address);

        jLabel_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_id.setText("----");

        buttonGroup1.add(jRadioButton_on);
        jRadioButton_on.setSelected(true);
        jRadioButton_on.setText("Đang hoạt động");

        buttonGroup1.add(jRadioButton_off);
        jRadioButton_off.setText("Ngưng hoạt động");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton_add.setText("Thêm");

        jButton_update.setText("Sửa");

        jButton_reset.setText("Làm mới");

        jButton_delete.setText("Xóa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_reset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_add)
                .addGap(18, 18, 18)
                .addComponent(jButton_update)
                .addGap(18, 18, 18)
                .addComponent(jButton_delete)
                .addGap(18, 18, 18)
                .addComponent(jButton_reset)
                .addGap(22, 22, 22))
        );

        jButton_save.setText("Save");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField_phone, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(jTextField_name))
                    .addComponent(jLabel_id, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton_on, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton_off)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_save, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_on)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel5)
                                .addComponent(jLabel_id))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 5, Short.MAX_VALUE)
                                .addComponent(jButton_save)
                                .addGap(4, 4, 4)
                                .addComponent(jRadioButton_off)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addGap(15, 15, 15))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jTabbedPane_history.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Tên KH", "SĐT", "ĐỊa chỉ", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_customer);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_search.setText("Tìm kiếm");

        jSpinner_filter.setModel(new javax.swing.SpinnerListModel(new String[] {"All", "Đang hoạt động", "Ngừng hoạt động"}));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Lọc");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(64, Short.MAX_VALUE)
                        .addComponent(jButton_search)
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_search)
                            .addComponent(jSpinner_filter))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jButton_search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSpinner_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane_history.addTab("Khách hàng", jPanel8);

        jTable_history.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Tên KH", "SĐT", "Ngày giao dịch", "Tên SP", "Số lượng", "Giá bán", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable_history);

        javax.swing.GroupLayout jPanel_historyLayout = new javax.swing.GroupLayout(jPanel_history);
        jPanel_history.setLayout(jPanel_historyLayout);
        jPanel_historyLayout.setHorizontalGroup(
            jPanel_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_historyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_historyLayout.setVerticalGroup(
            jPanel_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_historyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane_history.addTab("Lich sử giao dịch", jPanel_history);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane_history)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane_history)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JButton jButton_save;
    private javax.swing.JButton jButton_search;
    private javax.swing.JButton jButton_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel_history;
    private javax.swing.JRadioButton jRadioButton_off;
    private javax.swing.JRadioButton jRadioButton_on;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner_filter;
    private javax.swing.JTabbedPane jTabbedPane_history;
    private javax.swing.JTable jTable_customer;
    private javax.swing.JTable jTable_history;
    private javax.swing.JTextArea jTextArea_address;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_phone;
    private javax.swing.JTextField jTextField_search;
    // End of variables declaration//GEN-END:variables

    public int rowIndex = -1;
    
    public void act(){
        ActionListener actionListener = new JPanelCustomerController(this);
        jButton_add.addActionListener(actionListener);
        jButton_update.addActionListener(actionListener);
        jButton_delete.addActionListener(actionListener);
        jButton_reset.addActionListener(actionListener);
        jButton_search.addActionListener(actionListener);
        jRadioButton_off.addActionListener(actionListener);
        jRadioButton_on.addActionListener(actionListener);
        jButton_save.addActionListener(actionListener);
        
        ChangeListener changeListener = new JPanelCustomerController(this);
        jSpinner_filter.addChangeListener(changeListener);

        MouseListener mouseListener = new JPanelCustomerController(this);
        jTable_customer.addMouseListener(mouseListener);

    }
    public void table(ArrayList<Customer> arrayList){

            DefaultTableModel defaultTableModel = new DefaultTableModel(){
                public boolean isCellEditable(int row, int column){  
                    return false;  
                }
            };

            jTable_customer.setModel(defaultTableModel);
            
            defaultTableModel.addColumn("Mã KH");
            defaultTableModel.addColumn("Tên KH");
            defaultTableModel.addColumn("SĐT");
            defaultTableModel.addColumn("Địa chỉ");
            defaultTableModel.addColumn("Trạng thái");

            for(Customer customer : arrayList){               
                defaultTableModel.addRow(customer.getToTable());                
            }
            
    }
    public void insert(){
        String name = jTextField_name.getText();
        String phone = jTextField_phone.getText();
        String address = jTextArea_address.getText();
        boolean status = jRadioButton_on.isSelected();
        if(!name.isBlank() && !phone.isBlank() && !address.isBlank()){
            for(int i=0;i<phone.length();i++){
                if(phone.charAt(i)<'0' || phone.charAt(i)>'9'){
                    return;
                }
            }
            Customer customer = new Customer( name, address, phone, status);   
            CustomerDAO.getInstance().insert(customer);
        }
        table(CustomerDAO.getInstance().selectAll());
        
    }
    public void update(){
        try{
            rowIndex = jTable_customer.getSelectedRow();
            String id = String.valueOf(jTable_customer.getValueAt(rowIndex, 0));
            String name = String.valueOf(jTable_customer.getValueAt(rowIndex, 1));
            String phone = String.valueOf(jTable_customer.getValueAt(rowIndex, 2));
            String address = String.valueOf(jTable_customer.getValueAt(rowIndex, 3));
            String status = String.valueOf(jTable_customer.getValueAt(rowIndex, 4));

            jLabel_id.setText(id);
            jTextField_name.setText(name);
            jTextField_phone.setText(phone);
            jTextArea_address.setText(address);
            if(status.equals("Đang hoạt động")){
                jRadioButton_on.setSelected(true);
            }
            else{
                jRadioButton_off.setSelected(true);
            }
            jButton_save.setVisible(true);
            
        }catch(java.lang.ArrayIndexOutOfBoundsException e){
            return;
        }


    }
    public void save(){
        int id = Integer.valueOf(jLabel_id.getText());
        String name = jTextField_name.getText();
        String phone = jTextField_phone.getText();
        String address = jTextArea_address.getText();
        boolean status = jRadioButton_on.isSelected();
        if(!name.isBlank() && !phone.isBlank() && !address.isBlank()){
            for(int i=0;i<phone.length();i++){
                if(phone.charAt(i)<'0' || phone.charAt(i)>'9'){
                    return;
                }
            }
            Customer customer = new Customer( id, name, address, phone, status);   
            CustomerDAO.getInstance().update(customer);
        }
        table(CustomerDAO.getInstance().selectAll());
        jButton_save.setVisible(false);
        reset();
    }
    public void reset(){
        jLabel_id.setText("----");
        jTextField_name.setText("");
        jTextField_phone.setText("");
        jTextArea_address.setText("");
        jRadioButton_off.setSelected(false);
        jRadioButton_on.setSelected(true);
        jButton_save.setVisible(false);
        jTextField_search.setText("");
        jSpinner_filter.setValue("All");
        table(CustomerDAO.getInstance().selectAll());
    }
    public void delete(){
        try{
            rowIndex = jTable_customer.getSelectedRow();
            int id = Integer.valueOf(String.valueOf(jTable_customer.getValueAt(rowIndex, 0)));
            CustomerDAO.getInstance().delete(CustomerDAO.getInstance().selectById(id));
            table(CustomerDAO.getInstance().selectAll());
            
        }catch(java.lang.ArrayIndexOutOfBoundsException e){
            return;
        }
    }
    public void search(){
        String str = jTextField_search.getText();
        table(CustomerDAO.getInstance().search(str));
    }
    public void filter(){
        ArrayList<Customer> customers_search = CustomerDAO.getInstance().search(jTextField_search.getText());
        String str = (String) jSpinner_filter.getValue();
        String bool;
        if(str.equals("All")){
            table(customers_search);
            return;
        }
        if(str.equals("Đang hoạt động")){
            bool = "1";
        }
        else{
            bool = "0";
        }
        ArrayList<Customer> customer_filter = CustomerDAO.getInstance().filter(bool);
        ArrayList<Customer> result = new ArrayList<>();
        for(Customer customer: customer_filter){
            if(customers_search.contains(customer)){
                result.add(customer);
            }
        }
        table(result);
    }
    public void select_history(){
        DefaultTableModel defaultTableModel = new DefaultTableModel(){
            public boolean isCellEditable(int row, int column){  
                return false;  
            }
        };
        jTable_history.setModel(defaultTableModel);

        defaultTableModel.addColumn("Mã hóa đơn");
        defaultTableModel.addColumn("Tên KH");
        defaultTableModel.addColumn("SĐT");
        defaultTableModel.addColumn("Ngày giao dịch");
        defaultTableModel.addColumn("Tên SP");
        defaultTableModel.addColumn("Số lượng");
        defaultTableModel.addColumn("Giá bán");
        defaultTableModel.addColumn("Tổng tiền");

        try{
            int index = jTable_customer.getSelectedRow();
            String customer_id =String.valueOf(jTable_customer.getValueAt(index, 0));
            for(Object[] objects : CustomerDAO.getInstance().select_history(customer_id)){               
                defaultTableModel.addRow(objects);                
            }
            jTabbedPane_history.setSelectedIndex(1);
        }catch(java.lang.ArrayIndexOutOfBoundsException e){
            return;
        }
    }
    

 
    
}

